title: 2021 Dev Blog
author: Nathan Mai
email: doomsday9200@gmail.com
description: >
  This is a blog that i have created to showcase the things
  i learned and created in my 2021 coding class.

# social links
twitter_username: Null
github_username:  Maliceous

show_excerpts: true 
theme: minima
